//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrobotsCS.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrobotsCS.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Alive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alive {
            get {
                return ResourceManager.GetString("Alive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Crobots - Robot Battle Arena に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battle Complete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BattleComplete {
            get {
                return ResourceManager.GetString("BattleComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battle in Progress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BattleInProgress {
            get {
                return ResourceManager.GetString("BattleInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battle Speed: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BattleSpeed {
            get {
                return ResourceManager.GetString("BattleSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cycle: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cycle {
            get {
                return ResourceManager.GetString("Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dead に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dead {
            get {
                return ResourceManager.GetString("Dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error loading robot: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorLoadingRobot {
            get {
                return ResourceManager.GetString("ErrorLoadingRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Health に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Robot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadRobotButton {
            get {
                return ResourceManager.GetString("LoadRobotButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Robot Script に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadRobotDialog {
            get {
                return ResourceManager.GetString("LoadRobotDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   At least two robots are required to start a battle. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MinimumTwoRobots {
            get {
                return ResourceManager.GetString("MinimumTwoRobots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Robot Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RobotName {
            get {
                return ResourceManager.GetString("RobotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C# Script Files (*.cs)|*.cs|All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RobotScriptFilter {
            get {
                return ResourceManager.GetString("RobotScriptFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Battle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StopButton {
            get {
                return ResourceManager.GetString("StopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Winner: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
    }
}
